### ISSUE TITLE
Sending patch to Pacer does not work for firmware v10112

### ISSUE THREAD

**Issue by edmundofuentes** [francoisgeorgy/pacer-editor#10]
Hello François,

I recently updated my Pacer to the latest firmware v10112 and the "send patch to pacer" functionality broke.

After sending the patch to the Pacer, the lower 3 dots in the LCD start to blink and the preset it not automatically stored.  I can "force save" the patch by going to the save menu after receiving the patch, but even then only the buttons 1,2&3 are stored, the rest of the buttons retain their previous configuration.

This is the .syx path I'm trying to send: https://www.edmundofuentes.com/assets/posts/2020-06-05-boss-rc-202-nektar-pacer-midi-foot-controller/netkar-pacer-patch-rc202.2020-06-10-033223.syx

I believe that something is failing when updating the button 4 that is halting the update procedure.  Still, I cannot see any error on the Editor nor in the Pacer.

I've already written to Netkar's Support to see if they changed their MIDI Sysex implementation in the new firmware. I'll let you know if they reply with anything useful.

Also, let me know if I can help in any way. I've written a couple of utilities for MIDI in various languages, but never using the WebMIDI API in JS.  Still, I'm looking at the code and figuring things out.

Thanks in advance,
Cheers!

**Comment by francoisgeorgy** [comment]
Hi,
Thanks for using my Pacer editor.
I developed this editor with my Pacer loaded with firmware 10112.
I can reproduce your problem with my Pacer.
I'll try to debug as soon as possible. Unfortunately, at the moment, I have very little time do to that.
Regarding the code, well, it's the second project I did with webmidi, the first with webmidi+react. And, to be honest, the code is bad. I haven't used the editor for months and now I wonder how I could implement something so bad. I really must think about a version 2. 
I'll update this ticket as soon as I found something regarding this problem.
Kind regards

**Comment by edmundofuentes** [comment]
Thanks for the quick reply! Let me know if you're up to a v2.0, I'll gladly help!

I've been playing with the settings and debugging my specific .syx file, and I believe I've found the problem with my patch on the Relay settings.

On my patch there were two things wrong:

1. I had tried to configure the Relay Mode as N.O. (normally open) setting a "0" on the Data 1 field, since it's the first type listed in the manual and I assumed it was 0-indexed.
2. I thought the Relay Number (Data 2) was 1-indexed for some reason.

However, I played around with the configurations directly on the Pacer and then reading it into the Editor and this is what I found (this is on the newest firmware 10112): 

**Relay Modes (Data 1)**
N.O.: 1
N.C.: 2
Lat.: 3

**Relay Number (Data 2)**
Relay 1: 0
Relay 2: 1
Relay 3: 2
Relay 4: 3


I think that the new Pacer firmware changed the "relay mode" enum, or at least it has some kind of on-device validation, which did not exist previously but on the newest version was halting the procedure.

Here's the new .syx file I created, which is now working perfectly on my Pacer: https://www.edmundofuentes.com/assets/posts/2020-06-05-boss-rc-202-nektar-pacer-midi-foot-controller/nektar-pacer-patch-rc202.2020-06-13-161935.syx

If you don't mind, I will be submitting a PR with some extra details in the Readme.

Thanks again,
Cheers!

**Comment by edmundofuentes** [comment]
I'm closing this issue since it's a user/input data related issue and the editor is working as intended. I've added some info in the home screen to aid the user when configuring some options. 

https://github.com/francoisgeorgy/pacer-editor/pull/11

**Comment by francoisgeorgy** [comment]
Hi,
I updated the Pacer editor with lots of bug fixes and a improved and faster interface. This is something I had in the pipe for quite a while but had not found the time to do until this week-end.
You can have a preview at https://francoisgeorgy.github.io/pacer-editor/
Let me know if you find any issue.
Kind regards

**Comment by edmundofuentes** [comment]
Hello François!

I’m sorry for the late reply, I was away from home for a month so I couldn’t play with my Pacer.

I’ve tested the new version and messed around with it for a little while, and everything seems to be working okay! It looks a lot cleaner and more polished.

Thanks again for the great work, let me know if I can be of more help.

Cheers!

--
Edmundo Fuentes

**Comment by francoisgeorgy** [comment]
Hi Edmoundo,

Don't be sorry. Time flies too fast for everybody.

I really appreciate you took the time to checkout the new version of the
editor. Thank you very much.

I found a bug in the Pacer (impossible to read the D6 preset with midi) and
I had the opportunity to chat with a support guy from Nektar. They will
release a new firmware with a fix as well as some new features. The Pacer
should be even better and the editor too because this firmware update will
allow the editor to select the preset in the Pacer. This will really
improve the editing process.

I'll let you known when a new version is ready.

Take care. Cheers
François
