### ISSUE TITLE
Pacer web ab problem setting STEP inc/dec

### ISSUE THREAD

**Issue by robkoper** [francoisgeorgy/pacer-editor#13]
Hi,
Nice web utility!! I only have one problem: I can not set the target when I select STEP inc/dec. It will always return to the default value that was set when selecting this function.
Best,
Rob

**Comment by francoisgeorgy** [comment]
Hi!
Thank you for your support.
And good catch! There was indeed a bug.
I've fixed it. However I don't have my Pacer with me at the moment and can't test with the hardware. But I'm confident the problem is fixed.
I'll keep this issue open until I have tested with the hardware.

**Comment by robkoper** [comment]
Ah good! I will test it tomorrow,
Rob

**Comment by robkoper** [comment]
Hi Francois,

Tested, the settings work, but there is now another bug: when you 'walk' through the steps, the order is: step 1, 4,3,2 en 1 again, instead of 1,2,3,4.

Best,
Rob

**Comment by robkoper** [comment]
Hi, not true! No bug happily. I had set data 2 to 127 instead of 0.
So, thanks anyway!
Rob

**Comment by francoisgeorgy** [comment]
Great! Thanks a lot for the feedback.

I'll let you know when a new version is available.

Cheers
