### ISSUE TITLE
MIDI channel map incomplete

### ISSUE THREAD

**Issue by Nakedhoof** [francoisgeorgy/pacer-editor#3]
You are probably already aware that channel 16 is not available for any messages using this editor. I am finding it to be very useful, and if I can assist in any way, please do not hesitate to ask. I'm using channel 16 for lighting control, so it is very important for me to have this functionality. At first, I thought that perhaps the mapping started with channel 1 = channel 0 in the drop-down box. It took some experimentation to find this was an incorrect assumption.

Best regards,

William T Anderson
www.giantsofcolossus.com
www.nakedhoof.com

**Comment by francoisgeorgy** [comment]
Hi,
The channel is a 4 bit number. So we have 0 to 15. But, you are right, the editor should display 1..16 instead of 0..15. 

If you select channel 15 in the editor, that does not work for you?

Anyway I'll have a look to be sure there is no bug with the midi channel selection.

I develop this editor in my spare time, so forgive me if I don't always reply quickly.

Best Regards
Francois Georgy

**Comment by ElVicente** [comment]
Hi François

First thanks a million time for taking time to write this editor! It's seems so great!

I missed the 16th channel for my use too...
I did not understood in your above response if you plan to add that channel in the list or if it will remain as it is already.

**Comment by francoisgeorgy** [comment]
I added channel 16 in the editor. I did not pay enough attention to the channel management of the Pacer and missed the fact that channel 0 means "global channel" and values 1 to 16 are regular channels.

Version 0.9.3 fixes this problem.

**Comment by ElVicente** [comment]
Nice thank you!

Le lun. 15 juin 2020 à 21:00, François Georgy <notifications@github.com> a
écrit :

**Comment by francoisgeorgy** [comment]
Hi,
I updated the Pacer editor with lots of bug fixes and a improved and faster interface.
You can have a preview at https://francoisgeorgy.github.io/pacer-editor/
Let me know if you find any issue.
Kind regards
