### ISSUE TITLE
Program Step entry writes incomplete/erroneous info

### ISSUE THREAD

**Issue by nemonster** [francoisgeorgy/pacer-editor#4]
Steps to reproduce:
1. Add a step with the Program Step type.
2. You won't see an entry for the data bit (1/0) necessary to make it increment or decrement.
3. No matter what  you enter in the start/stop fields when you go into the manual editor you see that the start is always the largest value and the stop is 0.

You can go in after the fact in manual mode and correct it, and once that's done the corrections aren't overwritten. So it's not the end of the world but it _is_ kind of annoying.

**Comment by francoisgeorgy** [comment]
Nice catch, thank you. I'll fix this asap.

**Comment by francoisgeorgy** [comment]
I finally found some time to fix this.
In fact, the Pacer doc is incorrect. I will contact Nektar.
The start and end values have to be stored in bytes 2 and 3. Byte number 1 is not used. 
Version 0.9.1 is online now with this fix.
